/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package estudiantes;

import estudiantes.Estudiantes;
import javax.swing.JOptionPane;

public class Esquema extends javax.swing.JFrame {
private final Estudiantes control = new Estudiantes();
    /**
     * Creates new form Esquema
     */
    public Esquema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtNControl = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtCar = new javax.swing.JTextField();
        TxtProm = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        BtnListar = new javax.swing.JButton();
        PanelListado = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setText("REGISTRO DE ESTUDIANTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel2.setText("Num. Control:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 78, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 118, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel4.setText("Carrera:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 158, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel5.setText("Promedio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 198, -1, -1));
        getContentPane().add(TxtNControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 75, 139, -1));
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 115, 139, -1));
        getContentPane().add(TxtCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 155, 139, -1));
        getContentPane().add(TxtProm, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 195, 139, -1));

        BtnGuardar.setBackground(new java.awt.Color(204, 204, 255));
        BtnGuardar.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGuardarMouseClicked(evt);
            }
        });
        getContentPane().add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 235, 84, 40));

        BtnListar.setBackground(new java.awt.Color(204, 204, 255));
        BtnListar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        BtnListar.setText("Listar");
        BtnListar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnListarMouseClicked(evt);
            }
        });
        getContentPane().add(BtnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 85, 40));

        javax.swing.GroupLayout PanelListadoLayout = new javax.swing.GroupLayout(PanelListado);
        PanelListado.setLayout(PanelListadoLayout);
        PanelListadoLayout.setHorizontalGroup(
            PanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        PanelListadoLayout.setVerticalGroup(
            PanelListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        getContentPane().add(PanelListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGuardarMouseClicked
        try {
        String controlNum = TxtNControl.getText();
        String nombre = TxtNombre.getText();
        String carrera = TxtCar.getText();
        double promedio = Double.parseDouble(TxtProm.getText());

        // Guardar usando tu clase Estudiantes
        control.agregar(controlNum, nombre, carrera, promedio);

        JOptionPane.showMessageDialog(this, "Guardado correctamente");

        // Limpiar campos
        TxtNControl.setText("");
        TxtNombre.setText("");
        TxtCar.setText("");
        TxtProm.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error en los datos");
    }
    }//GEN-LAST:event_BtnGuardarMouseClicked

    private void BtnListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnListarMouseClicked
         PanelListado.removeAll();
    PanelListado.setLayout(new java.awt.BorderLayout());

    String[] columnas = {"Control", "Nombre", "Carrera", "Promedio"};

    var lista = control.getListaOrdenada();

    Object[][] datos = new Object[lista.size()][4];

    for (int i = 0; i < lista.size(); i++) {
        Estudiantes.Estudiante e = lista.get(i);

        datos[i][0] = e.getControl();
        datos[i][1] = e.getNombre();
        datos[i][2] = e.getCarrera();
        datos[i][3] = e.getPromedio();
    }

    javax.swing.JTable tabla = new javax.swing.JTable(datos, columnas);
    javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tabla);

    PanelListado.add(scroll, java.awt.BorderLayout.CENTER);
    PanelListado.revalidate();
    PanelListado.repaint();
    }//GEN-LAST:event_BtnListarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Esquema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Esquema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Esquema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Esquema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Esquema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnListar;
    private javax.swing.JPanel PanelListado;
    private javax.swing.JTextField TxtCar;
    private javax.swing.JTextField TxtNControl;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtProm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
