/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agendacont;

import javax.swing.JOptionPane;
import agendacont.Controlador;
public class VistaAgenda extends javax.swing.JFrame {
    
    private Controlador control = new Controlador();

    public VistaAgenda() {
        initComponents();
        // Configuraciones adicionales
        this.setResizable(true);
        this.setSize(550, 520);
        this.setLocationRelativeTo(null);
        // Mejorar el panel para que acepte layout dinámico
        PanelMostrar.setLayout(new java.awt.BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtTel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        BtnAgregar = new javax.swing.JButton();
        BtnMostrar = new javax.swing.JButton();
        PanelMostrar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel1.setText("AGENDA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 22, 81, -1));

        jLabel2.setText("Nombre ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 59, 58, -1));
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 56, 143, -1));

        jLabel3.setText("Telefono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 106, 58, -1));
        getContentPane().add(TxtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 103, 143, -1));

        jLabel4.setText("E-mail:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 149, 58, -1));

        TxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 146, 143, -1));

        BtnAgregar.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        BtnAgregar.setText("Agregar");
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseClicked(evt);
            }
        });
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 198, -1, -1));

        BtnMostrar.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        BtnMostrar.setText("Mostrar");
        BtnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMostrarMouseClicked(evt);
            }
        });
        getContentPane().add(BtnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        javax.swing.GroupLayout PanelMostrarLayout = new javax.swing.GroupLayout(PanelMostrar);
        PanelMostrar.setLayout(PanelMostrarLayout);
        PanelMostrarLayout.setHorizontalGroup(
            PanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );
        PanelMostrarLayout.setVerticalGroup(
            PanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        getContentPane().add(PanelMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseClicked
   String nombre = TxtNombre.getText();
    String tel = TxtTel.getText();
    String email = TxtEmail.getText();

    if (nombre.isEmpty() || tel.isEmpty() || email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Llena todos los campos");
        return;
    }

    control.agregar(nombre, tel, email);

    JOptionPane.showMessageDialog(this, "Guardado correctamente");

    TxtNombre.setText("");
    TxtTel.setText("");
    TxtEmail.setText("");
    }//GEN-LAST:event_BtnAgregarMouseClicked

    private void BtnMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMostrarMouseClicked
       PanelMostrar.removeAll();
        PanelMostrar.setLayout(new java.awt.BorderLayout());

        String[] columnas = {"Nombre", "Teléfono", "Email"};
        var lista = control.listar();

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay contactos guardados");
            return;
        }

        Object[][] datos = new Object[lista.size()][3];
        for (int i = 0; i < lista.size(); i++) {
            datos[i][0] = lista.get(i)[0];
            datos[i][1] = lista.get(i)[1];
            datos[i][2] = lista.get(i)[2];
        }

        javax.swing.JTable tabla = new javax.swing.JTable(datos, columnas);
        tabla.setRowHeight(25);
        tabla.setShowGrid(true);
        tabla.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(tabla);
        scroll.setBorder(javax.swing.BorderFactory.createTitledBorder("📋 Contactos Registrados"));
        
        PanelMostrar.add(scroll, java.awt.BorderLayout.CENTER);
        PanelMostrar.revalidate();
        PanelMostrar.repaint();
    
    }//GEN-LAST:event_BtnMostrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnMostrar;
    private javax.swing.JPanel PanelMostrar;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
